# Generated by Django 6.0.1 on 2026-02-04 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_user_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referral_code',
        ),
    ]
