# Generated by Django 6.0.1 on 2026-02-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_business_user',
            field=models.BooleanField(default=False, help_text='Пользователь сам включил ведение бизнеса с компанией (отключить сам не может).', verbose_name='Бизнес-пользователь'),
        ),
    ]
