# Generated by Django 6.0.1 on 2026-02-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_is_business_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление')], db_index=True, max_length=10, verbose_name='Действие')),
                ('user_uuid', models.UUIDField(blank=True, db_index=True, help_text='Для delete может быть только в payload после удаления из БД.', null=True, verbose_name='UUID пользователя')),
                ('payload', models.JSONField(default=dict, help_text='Данные для выгрузки: uuid, email, is_business_user, referred_by_uuid и т.д.', verbose_name='Данные (JSON)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает выгрузки'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Очередь выгрузки пользователя',
                'verbose_name_plural': 'Очередь выгрузки пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
