# Generated by Django 6.0.1 on 2026-01-31 13:58

from django.db import migrations


def create_initial_attributes(apps, schema_editor):
    ProductAttribute = apps.get_model("catalog", "ProductAttribute")
    ProductAttributeValue = apps.get_model("catalog", "ProductAttributeValue")

    color, _ = ProductAttribute.objects.get_or_create(code="color", defaults={"name": "Цвет"})
    for val in ["Красный", "Синий", "Чёрный", "Белый", "Зелёный"]:
        ProductAttributeValue.objects.get_or_create(attribute=color, value=val)

    size, _ = ProductAttribute.objects.get_or_create(code="size", defaults={"name": "Размер"})
    for val in ["XS", "S", "M", "L", "XL"]:
        ProductAttributeValue.objects.get_or_create(attribute=size, value=val)


def reverse_attributes(apps, schema_editor):
    ProductAttribute = apps.get_model("catalog", "ProductAttribute")
    ProductAttribute.objects.filter(code__in=["color", "size"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_attributes, reverse_attributes),
    ]
