# Generated by Django 6.0.1 on 2026-01-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_add_initial_attributes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryAttribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_required", models.BooleanField(default=False, verbose_name="Обязателен")),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="category_attributes",
                        to="catalog.productattribute",
                        verbose_name="Атрибут",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="category_attributes",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Атрибут категории",
                "verbose_name_plural": "Атрибуты категории",
                "unique_together": {("category", "attribute")},
            },
        ),
        migrations.AddField(
            model_name="category",
            name="attributes",
            field=models.ManyToManyField(
                blank=True,
                related_name="categories",
                through="catalog.CategoryAttribute",
                to="catalog.productattribute",
                verbose_name="Атрибуты категории",
            ),
        ),
    ]
