# Generated by Django 6.0.1 on 2026-01-31 16:12

from django.db import migrations, models


def rebuild_tree(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    try:
        Category.objects.rebuild()
    except Exception:
        # If rebuild isn't available for some reason, leave defaults.
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_category_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="lft",
            field=models.PositiveIntegerField(default=0, editable=False, db_index=True),
        ),
        migrations.AddField(
            model_name="category",
            name="rght",
            field=models.PositiveIntegerField(default=0, editable=False, db_index=True),
        ),
        migrations.AddField(
            model_name="category",
            name="tree_id",
            field=models.PositiveIntegerField(default=0, editable=False, db_index=True),
        ),
        migrations.AddField(
            model_name="category",
            name="level",
            field=models.PositiveIntegerField(default=0, editable=False, db_index=True),
        ),
        migrations.RunPython(rebuild_tree, reverse_code=migrations.RunPython.noop),
    ]
