# Generated by Django 6.0.1 on 2026-02-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_product_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='pv',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Персональный объём (PV) для начисления кешбека.', max_digits=12, verbose_name='PV'),
        ),
    ]
