# Generated by Django 6.0.1 on 2026-02-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_sync_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Человекочитаемый номер (с 100000)', null=True, unique=True, verbose_name='Номер заказа'),
        ),
    ]
