# Generated by Django 6.0.1 on 2026-02-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_pv',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Итоговый персональный объём (PV) по заказу.', max_digits=12, verbose_name='PV заказа'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pv',
            field=models.DecimalField(decimal_places=2, default=0, help_text='PV позиции на момент покупки (снимок из варианта товара).', max_digits=12, verbose_name='PV'),
        ),
    ]
