# Generated by Django 6.0.1 on 2026-02-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cdek_city_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Код города СДЭК'),
        ),
        migrations.AddField(
            model_name='order',
            name='cdek_pvz_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Код ПВЗ СДЭК'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость доставки'),
        ),
    ]
